login_login:
    resource: "@LoginLoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# routing for FOSUser
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
